mitre-attack/attack-website

- CHANGELOG.md
- attack-theme/static/scripts/navigation.js
- attack-theme/templates/macros/navigation.html
Added an ID on the navigation macro for the `navigation.js` script to be able to correctly set the initial state.
Closes #8.
> Addressing incorrect initial state for the side-navigation on the cloud matrix page

- README.md
- attack-theme/static/scripts/analytics.js
- attack-theme/templates/general/base.html
Removed google analytics and google-site-verification from source code (which should only exist on the gh-pages branch). Updated README to fix typo and broken links.
Closes #11.
> Removed analytics, fixed some issues with README

- CHANGELOG.md
Updated the ATT&CK roadmap to latest version.
Closes #31.
> update roadmap to latest version

- CHANGELOG.md
Update ATT&CK content to version 6.2.
Closes #36.
> update ATT&CK content to version 6.2

- CHANGELOG.md
- modules/technique.py
Fixed incorrect inheritance from sub-technique siblings on sub-technique cards.
Closes #47.
> Fixed inconsistency in sub-technique cards

- CHANGELOG.md
- attack-theme/templates/groups/group.html
- attack-theme/templates/mitigations/mitigation.html
- attack-theme/templates/software/software.html
- attack-theme/templates/tactics/tactic.html
- attack-theme/templates/techniques/technique.html
- modules/group.py
- modules/mitigation.py
- modules/software.py
- modules/tactic.py
- modules/technique.py
- modules/util.py
Added created and last modified dates to cards on object pages. 
Closes #38.
> Adding created and last modified dates to object pages

- attack-theme/templates/general/base.html
- attack-theme/templates/macros/navigation.html
- attack-theme/templates/resources/resources.html
- modules/config.py
- modules/matrix.py
- modules/redirects.py
- modules/util.py
Added links and redirects for ATT&CK for ICS
> add ATT&CK for ICS links

- CHANGELOG.md
- modules/config.py
Added redirects for matrix poster and roadmap.
Resolves #85.
> added redirects for matrix poster and roadmap

- attack-theme/static/style/_matrix.scss
- attack-theme/templates/general/attack-index.html
- attack-theme/templates/macros/matrix.html
- attack-theme/templates/matrices/matrix.html
- modules/config.py
- modules/matrix.py
1. Minor updates to matrix style when sub-techniques are not present and when multiple matrices are present in a domain. 
2. Updated index matrix to have cloud platforms
3. Added matrix timestamps using matrix object modified dates.
Closes #105 and #27.
> Feature/#105 #27 timestamps indexmatrix

- modules/technique.py
Added a few lines of code to techniques.py to sort various lists that before they are formatted into card-data information.
Resolves Issue #84
> sort lists within card-data

- attack-theme/templates/techniques/technique.html
- modules/config.py
Update page titles and navigator links for sub-techniques support.
Resolves #104 and #100.
> Feature/#104 #100 navlinks sub titles

- attack-theme/templates/groups/group.html
- attack-theme/templates/mitigations/mitigation.html
- attack-theme/templates/software/software.html
- attack-theme/templates/techniques/technique.html
- modules/search.py
Added nofollow, noindex to the head of deprecated objects to stop search engines from showing them. Deprecated objects will not be shown under our search either.
See #116.
> deprecated objects excluded from search

- attack-theme/templates/resources/contribute.html
- attack-theme/templates/resources/getting-started.html
- data/faq.json
- data/resources.json
Update philosophy paper links to internal doc 
See #128.
> update philosophy paper to use internal links

- CHANGELOG.md
- content/pages/updates/updates-march-2020.md
Fixing technique count on March 2020 update. 
Closes #141.
> Updating March technique count

- CHANGELOG.md
- content/pages/updates/updates-march-2020.md
Added Navigator layers to the changelog of the sub-techniques update
Closes #126
> Added navigator layers to sub-technique update changelog

- CHANGELOG.md
- attack-theme/templates/resources/contribute.html
Update contribute page on develop branch
See #162.
> update contribute page

- CHANGELOG.md
- attack-theme/templates/macros/navigator.html
- modules/site_config.py
Fixed navigator layer links.
Closes #169.
> Fixing navigator layer links

- CHANGELOG.md
- update-attack.py
Modules and tests flags from `update-attack.py` now require arguments.
Closes #177.
> Adding robustness to flag arguments

- CHANGELOG.md
- attack-theme/templates/macros/navigator.html
- modules/tour/tour_config.py
- modules/website_build/website_build_config.py
Fixed issue that prevented subdirectory module from updating navigator layer links. 
Closes #170.
> Adding subdirectory support for navigator layer links

- CHANGELOG.md
- attack-theme/templates/general/base.html
- attack-theme/templates/macros/navigator.html
- modules/config.py
Fixes layer links on master branch.
Fixes #169, #192.
> fix layer link bug in master

- CHANGELOG.md
- attack-theme/templates/groups/group.html
- attack-theme/templates/software/software.html
Contributor lists are now delimited with semicolons on group and software pages
Closes #196
> fixed contributor delimitor to use semicolons

- CHANGELOG.md
- attack-theme/templates/general/base.html
- content/pages/updates/updates-october-2019.md
- data/versions.json
- modules/config.py
Fixed end date for v6
See #204
> fixed end date for v6

- CHANGELOG.md
- modules/citationchecker.py
Updated citation test to find malformed citations which don't have a space after the colon, e.g `(Citation:foobar)` which _should_ be `(Citation: foobar)`.
Resolves #209, however MITRE/CTI data will require a patch for the broken citations discovered by the updated tests.
> Updated citation tests to catch more types of malformed citations

- CHANGELOG.md
- attack-theme/static/scripts/tour/tour-versions.js
Fixes a loop that occurs in the site tour on the versions of ATT&CK page.
Resolves #203.
> Fix tour loop

- CHANGELOG.md
- content/pages/updates/updates-july-2020.md
add links to july2020 Navigator layers from release notes
Resolves #208 and https://github.com/mitre-attack/attack-navigator/issues/194
> add links to july2020 Navigator layers from release notes

- CHANGELOG.md
- attack-theme/templates/resources/contribute.html
updated contribute page with new "contribution update" card
Resolves #207
> updated contribute page with new "contribution update" card

- CHANGELOG.md
- attack-theme/static/style/_layouts.scss
- attack-theme/templates/general/base.html
- attack-theme/templates/resources/changelog.html
- data/stix/mobile-attack.json
- data/stix/pre-attack.json
- data/versions.json
- modules/config.py
Stage release notes for ATT&CK v7.1, and other minor changes.
Resolves #214, #215, #216.
> add documentation for ATT&CK v7.1

- CHANGELOG.md
- attack-theme/templates/general/base.html
- attack-theme/templates/resources/training-cti.html
- modules/config.py
Adds notes to CTI training page noting that ATT&CK v6 should be used instead of ATT&CK v7.
Resolves #221.
> add notes to CTI training page that ATT&CK v6 should be used

- CHANGELOG.md
- modules/matrices/matrices_config.py
- modules/website_build/website_build_config.py
Adds matrix for the Network platform. Ports trademark fixes into matrix module.
Resolves #230.
> add network matrix

- modules/random_page/random_page.py
- modules/random_page/random_page_config.py
- modules/tests/tests_config.py
Cleaned up code and changed the build priority of the random_page module (and adjusted the test module priority to accommodate) to fix the broken "Random Page" feature on the homepage.
> Fix random_page feature

- CHANGELOG.md
- modules/matrices/matrices_config.py
Added PRE platform.
Closes #251
> Adding PRE platform

- attack-theme/templates/macros/navigator.html
- modules/groups/groups.py
- modules/matrices/matrices.py
- modules/matrices/templates/matrix.html
- modules/site_config.py
- modules/software/software.py
- modules/util/buildhelpers.py
- modules/website_build/website_build_config.py
Added navigator 4.0 support.
Closes #258 and #259
> Updating to navigator 4.0

- modules/website_build/website_build_config.py
Adding PRE platform to homepage.
Closes #254.
> Adding PRE platform to homepage

- CHANGELOG.md
- data/stix/mobile-attack.json
- data/stix/pre-attack.json
- data/versions.json
- modules/matrices/matrices_config.py
- modules/resources/static_pages/updates-july-2020.md
- modules/resources/static_pages/updates-october-2020.md
Update the website to use ATT&CK version 8.
> Update to ATT&CK version 8

- CHANGELOG.md
- data/versions.json
- modules/resources/static_pages/updates-october-2020.md
Update website to use ATT&CK v8.1
> Attack v8.1

- CHANGELOG.md
- attack-theme/templates/general/base-template.html
- data/versions.json
- modules/resources/static_pages/updates-october-2020.md
- modules/resources/templates/getting-started.html
- modules/util/buildhelpers.py
- modules/website_build/static_pages/terms-of-use.md
- modules/website_build/templates/terms-of-use.html
- modules/website_build/website_build_config.py
- Updated Navigator layers to version 4.1 so that users are no longer warned that they are out of date.
- Updated introductory video on [getting started](https://attack.mitre.org/resources/getting-started/) page.
- Updated ATT&CK data to v8.2.
> ATT&CK v8.2 / Website version 3.1

- CHANGELOG.md
- modules/groups/templates/groups-index.html
- modules/software/templates/software-index.html
- modules/techniques/templates/technique.html
Adding ID to all tables
Closes #235, #236
> Adding ID to all tables

- CHANGELOG.md
- modules/mitigations/mitigations.py
- modules/mitigations/templates/mitigation.html
- modules/util/buildhelpers.py
Added navigator support for mitigations. Updated navigator layer version 4.2.
Closes #234
> Navigation mitigation layers

- requirements.txt
Updating requirements.txt to account for new version of mitreattack-python (1.1.0 from 1.0.0)
* Fixes issue with some backend utilities failing during build due to bugs in older versions of mitreattack-python
> bump mitreattack-python version

- CHANGELOG.md
- modules/resources/resources.py
- modules/resources/templates/training-cti.html
- modules/website_build/website_build_config.py
Adding missing groups excel link from ATT&CK in Excel.
Fixing CTI training ticket number 4473845 -> 473845
> Website 3.2.2: Missing groups link excel, and CTI training number

- CHANGELOG.md
- modules/tests/linkchecker.py
Updates the external link tests.
- Will now report any non 200 responses from external links
- Will now print a more descriptive error when a link is broken (e.g the exact response code).
> update external link tests

- CHANGELOG.md
- modules/attack_redirections/attack_redirections.py
- modules/attack_redirections/attack_redirections_config.py
- modules/matrices/matrices.py
- modules/software/software.py
- modules/tactics/tactics.py
- modules/techniques/techniques.py
- modules/tour/tour.py
- modules/util/buildhelpers.py
- modules/util/stixhelpers.py
Added domain checks for tactics, software, and mitigations objects.
Sorted sub-techniques by ATT&CK ID on Techniques Used tables.
Closes #310, #314.
> Feature/#310 and #314

- modules/attack_redirections/attack_redirections.py
- modules/attack_redirections/attack_redirections_config.py
- modules/matrices/matrices.py
- modules/tour/tour.py
- modules/util/stixhelpers.py
Removing duplicates in ATT&CK redirections, minor fix to tour.
Issue #304 was already closed.
> Removing duplicates in ATT&CK redirections, fixing tour

- CHANGELOG.md
- Dockerfile
- modules/website_build/website_build_config.py
Update docker file and add docs for v3.2.3.
Fixes #313
> Fix dockerfile

- CHANGELOG.md
- attack-theme/static/scripts/site.js
- attack-theme/static/style/_layouts.scss
- attack-theme/static/style/_nav.scss
- attack-theme/templates/general/404.html
- attack-theme/templates/general/attack-index.html
- attack-theme/templates/general/base-template.html
- attack-theme/templates/general/intro-overview.html
- attack-theme/templates/general/two-column.html
- attack-theme/templates/macros/navigation.html
- attack-theme/templates/macros/navigation_menu.html
- modules/contribute/templates/contribute.html
- modules/groups/templates/group.html
- modules/groups/templates/groups-index.html
- modules/mitigations/templates/mitigation.html
- modules/mitigations/templates/mitigations-domain-index.html
- modules/resources/templates/training-cti.html
- modules/resources/templates/training.html
- modules/software/templates/software-index.html
- modules/software/templates/software.html
- modules/tactics/templates/tactic.html
- modules/tactics/templates/tactics-domain-index.html
- modules/techniques/templates/technique.html
- modules/techniques/templates/techniques-domain-index.html
- Improved side navigation elements:
- Side-navs now scroll independently of the main page contents, making it easier to work with long pages.
- The side-nav title (e.g "mitigations") will now stay in the view when scrolled.
- The side-nav will now scroll to the active page link when initialized.
- Improvements to site maintainability by improving the page HTML templates.
> Sidebar scrolling improvements

- attack-theme/static/scripts/site.js
- attack-theme/static/style/_nav.scss
- attack-theme/templates/general/two-column.html
Fixes issue with matrices in the _side_ layout where technique cells' handles would not be aligned properly.
> fix css classes intended for sidenav applying to matrix handles

- CHANGELOG.md
- modules/tactics/templates/tactics-domain-index.html
- modules/techniques/templates/techniques-domain-index.html
- modules/website_build/website_build_config.py
- Fixed footer on tactic list pages showing up as if it were sticky
- Fixed table scrolling on technique and tactic list pages
Resolves #339.
> Fix tactic list page

- CHANGELOG.md
- modules/util/buildhelpers.py
Updated ATT&CK Navigator and layer versions.
Closes #343.
> Updating navigator and layer versions

- CHANGELOG.md
- docs/RELEASE.md
- pyproject.toml
- requirements.txt
Needed due to updated dependency on mitreattack-python
> Update website to 3.6.7

- .dockerignore
- CHANGELOG.md
- Dockerfile
- data/versions.json
- modules/campaigns/templates/campaign.html
- modules/datasources/datasources.py
- modules/datasources/templates/datasource.html
- modules/groups/templates/group.html
- modules/resources/static_pages/updates-october-2022.md
- pyproject.toml
> Update website to 4.0.1

- .gitignore
- attack-theme/static/scripts/filter/filter.js
- attack-theme/templates/macros/matrix.html
- attack-theme/templates/macros/navigation.html
- modules/datasources/templates/datasource.html
- modules/matrices/__init__.py
- modules/resources/templates/getting-started.html
- modules/software/software.py
- modules/util/buildhelpers.py
- modules/util/relationshiphelpers.py
- modules/util/stixhelpers.py
- requirements.txt
> 90 update contact page to mention the attack website issue tracker

- attack-theme/static/style/_layouts.scss
- attack-theme/static/style/_nav.scss
> Printissue

- attack-theme/static/style/_layouts.scss
- modules/resources/templates/contact.html
- modules/versions/versions.py
> added contact info for attack website issue tracker

- modules/resources/templates/contact.html
Added ATT&CK Website issue tracker to the contact page
> added needed changes

- attack-theme/templates/macros/navigator.html
- modules/campaigns/campaigns.py
- modules/groups/groups.py
- modules/mitigations/mitigations.py
- modules/software/software.py
- modules/util/buildhelpers.py
> fix mismatched navigator layer filenames

- .github/dependabot.yml
Adds dependabot configuration file that targets `develop` branch and scans weekly
Closes #433
> 433 update dependabot configuration to target develop branch

- data/resources.json
- modules/resources/templates/getting-started.html
> fixed broken links per issue outline

- attack-theme/static/style/_layouts.scss
- attack-theme/static/style/_nav.scss
- attack-theme/templates/general/attack-index.html
- attack-theme/templates/macros/navigation.html
Arrow toggles with open and close of sidebar for mobile
The landing page for the website on mobile now displays correctly
Closes part of #450
> 450 sidebar mobile view fix

- modules/search/search.py
Allow search to find the new assets objects
> Add condition to generate assets.json to search.py

- custom_jinja_filters.py
Added a title attribute to reference markers which displays the title of a reference when a user hovers over a reference marker.
Closes issue #471
> add reference title to marker

- modules/resources/templates/contact.html
> update gh links

- data/resources_navigation.json
- modules/resources/__init__.py
- modules/resources/static_pages/learn-more-about-attack.md
- modules/resources/templates/learn-more-about-attack.html
This PR adds the learn more about att&ck page to the resources section
> Website updates learn more about attack page

- attack-search/package-lock.json
- attack-search/package.json
- Upgrade several attack-search npm dependencies per Dependabot. See commit messages for details.
- Built [Dockerfile](https://github.com/mitre-attack/attack-website/blob/master/Dockerfile) successfully on localhost
- Tested basic search functionality in Firefox and Chrome
> Dependabot change bundle
